EL_NAME = scientific
EL_VER = 6.7
EL_ARCH = x86_64
EL_BASEURL = http://mirror.karneval.cz/pub/linux/scientific/$(EL_VER)/$(EL_ARCH)
EL_REPOURL = $(EL_BASEURL)/os
EL_UPDATES = $(EL_BASEURL)/updates/security
EL_REL_RPM = $(EL_BASEURL)/os/Packages/sl-release-6.7-2.x86_64.rpm
EL_YUM_REPOS = $(shell ls -1 $(BUILDCONF)/overlay-root/etc/yum.repos.d/*.repo)
EL_GPG_KEYS = $(shell ls -1 $(BUILDCONF)/overlay-root/etc/yum.repos.d/RPM-GPG-KEY-*)
EL_RPMLIST = $(BUILDCONF)/rpms.list

