#!/bin/sh

read -r cmdline < /proc/cmdline

for param in $cmdline ; do
  case $param in
    root=*      ) root=${param#root=}             ;;
  esac
done

[ ! -d /fat32 ] && mkdir /fat32
if [ $root == "fat32" ]; then
  mount -t vfat `cat /.root-fat32` /fat32
else
  echo "*** Fetch vmlinuz"
  wget -qO /fat32/vmlinuz $root/vmlinuz
  echo "*** Fetch initrd"
  wget -qO /fat32/initrd $root/initrd
fi;


echo "*** Load new kernel and initrd"
kexec --initrd=/fat32/initrd --command-line="$cmdline" /fat32/vmlinuz -l > /dev/null
echo "*** Bye."
kexec -e
